# Compile the Go app using Alpine Golang image
FROM golang:alpine as builder
RUN mkdir /build/
ADD . /build/
WORKDIR /build/
# Tell go compiler to stastatically link the runtime libraries into the binary itself
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o .
# Create scratch image with only the binary
FROM scratch
COPY --from=builder /build/ /app/
WORKDIR /app/
EXPOSE 8080
ENTRYPOINT ["./ervcp"]